// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXwVO0Tr4qF9isff1Gc4AvMfZxRZgu7XA',
    appId: '1:759640552636:web:356ade4ae1238202b1ccb9',
    messagingSenderId: '759640552636',
    projectId: 'cataractapplication',
    authDomain: 'cataractapplication.firebaseapp.com',
    storageBucket: 'cataractapplication.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtuZJoJ1hQifIgBuS58YMWkasN-umGw_0',
    appId: '1:759640552636:android:bdf2444014f6076bb1ccb9',
    messagingSenderId: '759640552636',
    projectId: 'cataractapplication',
    storageBucket: 'cataractapplication.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ_D9RNJMOblYZM-7lY3_YMHc_6sJEKdE',
    appId: '1:759640552636:ios:6f6fbab8360e305cb1ccb9',
    messagingSenderId: '759640552636',
    projectId: 'cataractapplication',
    storageBucket: 'cataractapplication.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ_D9RNJMOblYZM-7lY3_YMHc_6sJEKdE',
    appId: '1:759640552636:ios:6f6fbab8360e305cb1ccb9',
    messagingSenderId: '759640552636',
    projectId: 'cataractapplication',
    storageBucket: 'cataractapplication.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXwVO0Tr4qF9isff1Gc4AvMfZxRZgu7XA',
    appId: '1:759640552636:web:53c0ccf2712ce4e9b1ccb9',
    messagingSenderId: '759640552636',
    projectId: 'cataractapplication',
    authDomain: 'cataractapplication.firebaseapp.com',
    storageBucket: 'cataractapplication.firebasestorage.app',
  );

}